#!/usr/bin/env bash
# Updates generated scripts with CLDR data

PATH_PLURAL=$(dirname "$0")/../src/common/media/lua/shared/OmiLibrary/Definition/Generated/CLDRPluralData.lua
PATH_DATETIME=$(dirname "$0")/../src/common/media/lua/shared/OmiLibrary/Definition/Generated/CLDRDateTimeData.lua

pz-extract-cldr plurals -o "$PATH_PLURAL"
pz-extract-cldr datetime -o "$PATH_DATETIME"
